# docker-compose.yml — это файл настройки связей. Он не строит код, он решает, как и с кем запускать уже готовые контейнеры.
# Для Docker Compose:

# Из каких частей состоит система? (App + DB + Redis?)

# Как они должны общаться? (depends_on, общая сеть создается сама).

# Какие порты открыть наружу? (ports)

# Где хранить важные данные, чтобы не исчезли? (volumes)

services:
  # 1. Сервис Базы Данных
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Чтобы можно было подключиться через DBeaver снаружи

  # 2. Сервис Вашего Приложения
  web:
    build: .
    restart: always
    ports:
      - "8000:5000"
    environment:
      # Самое важное: указываем путь к БД внутри сети Docker
      # Формат: postgresql://user:password@SERVICE_NAME:5432/dbname
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@db:5432/online_shop_db
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      # Не забудьте про ключи Stripe и секретный ключ Flask!
      # Лучше вынести их в .env файл, но для теста можно прописать тут
      SECRET_KEY: "oidsngoisdngiodsnoipngsdfopgsfd"
    env_file:
      - .flaskenv
    depends_on:
      - db
    volumes:
      # Маппинг папок, чтобы изменения кода на Windows сразу попадали в контейнер
      - .:/app
    command: python run.py

volumes:
  postgres_data: